[paths]
; 工具目录
picture_tools=tools/picture_tools
; 下面存储工具路径 文件或文件夹
stegosuite=stegosuite-0.7-win_amd64.jar
jpseek=jpseek.exe
Image_Steganography=Image Steganography
F5=F5-steganography
silenteye=silenteye/silenteye.exe
;stegpy=stegpy
;stegseek=stegseek

[ssh]
username=kali
password=kali
ip=192.168.80.135