[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "base45>=0.4.4",
    "base58>=2.1.1",
    "base91>=1.0.1",
    "bubblepy>=1.0",
    "ddddocr>=1.6.1",
    "fastapi>=0.141.1",
    "jinja2>=3.1.6",
    "jpype1>=1.7.1",
    "lxml-html-clean>=0.4.5",
    "opencv-python>=5.0.0.93",
    "pybase100>=0.3.1",
    "pycryptodome>=3.23.0",
    "python-multipart>=0.0.32",
    "pythonnet>=3.1.0",
    "requests-html>=0.10.0",
    "uvicorn>=0.52.3",
    "websockets==13.1",
    "wordninja>=2.0.0",
]
